apiVersion: v1
kind: ConfigMap
metadata:
  name: overpass-radio-apache-cors
  namespace: overpass-radio
data:
  zz-overpass-radio-cors.conf: |
    <Directory "/opt/overpass/cgi-bin/">
        Require all granted
    </Directory>

    <IfModule mod_headers.c>
        Header always unset Access-Control-Allow-Origin
        Header always set Access-Control-Allow-Origin "*"
        Header always set Access-Control-Allow-Methods "GET, POST, OPTIONS"
        Header always set Access-Control-Allow-Headers "Content-Type, Accept, X-Requested-With"
        Header always set Access-Control-Max-Age "600"
    </IfModule>
