apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overpass-radio-data
  namespace: overpass-radio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
